# -*- coding: utf-8 -*-
import json, os

OUT = "/tmp/kamal-campus/quiz"
os.makedirs(OUT, exist_ok=True)

def q(qid, diff, notion, enonce, choix, reponse, expl):
    assert len(choix) == 4 and len(set(choix)) == 4, (qid, choix)
    assert 0 <= reponse < 4
    assert expl
    return {"id": qid, "difficulte": diff, "notion": notion, "enonce": enonce,
            "choix": choix, "reponse": reponse, "explication": expl}

FILES = {}

# ---------- 01 cinquieme : découverte du latin ----------
FILES[1] = ("cinquieme", [
 q(1,"facile","declinaison-1","À quel cas correspond la forme « rosam » (1re déclinaison, singulier) ?",
   ["Nominatif","Génitif","Accusatif","Ablatif"],2,
   "La désinence -am du singulier de la 1re déclinaison marque l'accusatif : rosa, rosae, rosae, rosam, rosā."),
 q(2,"facile","vocabulaire","Que signifie le mot latin « aqua » ?",
   ["l'eau","la terre","le feu","l'air"],0,
   "« Aqua » signifie « l'eau » (cf. aquarium, aqueduc)."),
 q(3,"facile","conjugaison-sum","Quelle est la forme de « sum » (être) à la 1re personne du singulier au présent ?",
   ["es","est","sum","sumus"],2,
   "Le présent de sum : sum, es, est, sumus, estis, sunt. « je suis » = sum."),
 q(4,"facile","alphabet-grec","Quelle est la première lettre de l'alphabet grec ?",
   ["oméga","alpha","bêta","delta"],1,
   "L'alphabet grec commence par alpha (α) et se termine par oméga (ω)."),
 q(5,"facile","mythologie","Dans la mythologie romaine, qui est le roi des dieux ?",
   ["Neptune","Pluton","Jupiter","Mars"],2,
   "Jupiter (Zeus chez les Grecs) est le roi des dieux, maître du ciel et de la foudre."),
 q(6,"facile","civilisation","Selon la légende, qui a fondé la ville de Rome ?",
   ["Énée","Romulus","César","Auguste"],1,
   "La légende attribue la fondation de Rome à Romulus, en 753 av. J.-C."),
 q(7,"facile","declinaison-1","Quelle forme est le génitif singulier de « rosa » ?",
   ["rosa","rosae","rosam","rosarum"],1,
   "Le génitif singulier de la 1re déclinaison est en -ae : rosae (« de la rose »)."),
 q(8,"facile","vocabulaire","Que signifie le mot latin « puella » ?",
   ["le garçon","la jeune fille","la femme","la mère"],1,
   "« Puella » désigne la jeune fille ; « puer » désigne le garçon."),
 q(9,"moyen","cas-fonction","En latin, quel cas exprime la fonction de sujet ?",
   ["Le nominatif","L'accusatif","Le génitif","Le datif"],0,
   "Le nominatif est le cas du sujet (et de l'attribut du sujet)."),
 q(10,"facile","civilisation","Selon la légende, quel animal a allaité Romulus et Remus ?",
   ["une louve","une chèvre","une ourse","une jument"],0,
   "Une louve (lupa) aurait recueilli et allaité les jumeaux Romulus et Remus."),
 q(11,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 3e personne du pluriel au présent ?",
   ["est","estis","sunt","sumus"],2,
   "« ils sont » se dit « sunt » : sum, es, est, sumus, estis, sunt."),
 q(12,"facile","vocabulaire","Que signifie le mot latin « bellum » ?",
   ["la paix","la guerre","le livre","la ville"],1,
   "« Bellum » signifie « la guerre » (cf. belliqueux) ; la paix se dit « pax »."),
])

# ---------- 02 cinquieme ----------
FILES[2] = ("cinquieme", [
 q(1,"facile","declinaison-1","Quelle est la forme du nominatif pluriel de « rosa » ?",
   ["rosae","rosas","rosarum","rosis"],0,
   "Le nominatif pluriel de la 1re déclinaison est en -ae : rosae (« les roses »)."),
 q(2,"facile","vocabulaire","Que signifie le mot latin « terra » ?",
   ["la mer","la terre","le ciel","la route"],1,
   "« Terra » signifie « la terre » (cf. terrestre, territoire)."),
 q(3,"facile","conjugaison-amo","Quelle est la forme de « amo » (aimer) à la 2e personne du singulier au présent ?",
   ["amo","amas","amat","amamus"],1,
   "Présent d'amo : amo, amas, amat, amamus, amatis, amant. « tu aimes » = amas."),
 q(4,"facile","alphabet-grec","Comment se nomme la lettre grecque « π » ?",
   ["pi","phi","psi","rho"],0,
   "La lettre « π » se nomme « pi » ; elle correspond au son [p]."),
 q(5,"facile","mythologie","Quel dieu romain règne sur la mer ?",
   ["Jupiter","Pluton","Neptune","Apollon"],2,
   "Neptune (Poséidon chez les Grecs) est le dieu de la mer."),
 q(6,"facile","vocabulaire","Que signifie le mot latin « amicus » ?",
   ["l'ennemi","le maître","l'ami","le voisin"],2,
   "« Amicus » signifie « l'ami » (cf. amical, amitié)."),
 q(7,"moyen","cas-fonction","En latin, quel cas exprime le complément d'objet direct (COD) ?",
   ["Le nominatif","L'accusatif","Le datif","L'ablatif"],1,
   "L'accusatif est le cas du complément d'objet direct."),
 q(8,"facile","declinaison-1","Quelle forme est l'accusatif pluriel de « rosa » ?",
   ["rosae","rosas","rosarum","rosis"],1,
   "L'accusatif pluriel de la 1re déclinaison est en -as : rosas."),
 q(9,"facile","civilisation","En quelle année, selon la tradition, Rome a-t-elle été fondée ?",
   ["509 av. J.-C.","753 av. J.-C.","44 av. J.-C.","476 apr. J.-C."],1,
   "La tradition situe la fondation de Rome en 753 av. J.-C."),
 q(10,"facile","vocabulaire","Que signifie le mot latin « rex » ?",
   ["le roi","le dieu","le soldat","le père"],0,
   "« Rex » signifie « le roi » (génitif : regis ; cf. régner, royal)."),
 q(11,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 3e personne du singulier au présent ?",
   ["sum","es","est","sunt"],2,
   "« il/elle est » se dit « est »."),
 q(12,"facile","mythologie","Quelle déesse romaine est la déesse de l'amour et de la beauté ?",
   ["Junon","Minerve","Diane","Vénus"],3,
   "Vénus (Aphrodite chez les Grecs) est la déesse de l'amour et de la beauté."),
])

# ---------- 03 quatrieme ----------
FILES[3] = ("quatrieme", [
 q(1,"moyen","declinaison-2","Quel est le génitif singulier de « dominus » (2e déclinaison) ?",
   ["dominus","domini","domino","dominum"],1,
   "Le génitif singulier de la 2e déclinaison masculine est en -i : domini."),
 q(2,"moyen","vocabulaire","Que signifie le mot latin « servus » ?",
   ["le maître","l'esclave","le citoyen","le soldat"],1,
   "« Servus » signifie « l'esclave » ; le maître se dit « dominus »."),
 q(3,"moyen","conjugaison-amo","Quelle est la forme de « amo » à la 3e personne du pluriel au présent ?",
   ["amat","amamus","amatis","amant"],3,
   "« ils aiment » se dit « amant » : amo, amas, amat, amamus, amatis, amant."),
 q(4,"moyen","cas-fonction","En latin, quel cas exprime le complément du nom (possession) ?",
   ["Le nominatif","Le génitif","Le datif","L'accusatif"],1,
   "Le génitif exprime le complément du nom, notamment la possession."),
 q(5,"moyen","alphabet-grec","Comment se nomme la lettre grecque « δ » ?",
   ["delta","thêta","lambda","sigma"],0,
   "La lettre « δ » se nomme « delta » et correspond au son [d]."),
 q(6,"moyen","mythologie","Quel héros grec est célèbre pour ses douze travaux ?",
   ["Achille","Ulysse","Héraclès","Thésée"],2,
   "Héraclès (Hercule chez les Romains) est connu pour ses douze travaux."),
 q(7,"moyen","declinaison-2","Quel est l'accusatif singulier de « dominus » ?",
   ["domine","domini","dominum","domino"],2,
   "L'accusatif singulier de la 2e déclinaison masculine est en -um : dominum."),
 q(8,"moyen","civilisation","Comment appelait-on à Rome le lieu des combats de gladiateurs ?",
   ["le forum","les thermes","l'amphithéâtre","la basilique"],2,
   "Les combats de gladiateurs se déroulaient dans l'amphithéâtre (ex. le Colisée)."),
 q(9,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 1re personne du singulier à l'imparfait ?",
   ["eram","eras","erat","ero"],0,
   "L'imparfait de sum : eram, eras, erat... « j'étais » = eram."),
 q(10,"moyen","vocabulaire","Que signifie le mot latin « templum » ?",
   ["la maison","le temple","le marché","le théâtre"],1,
   "« Templum » signifie « le temple » (cf. temple)."),
 q(11,"difficile","declinaison-2","Quel est le vocatif singulier de « dominus » ?",
   ["dominus","domine","domino","domini"],1,
   "Le vocatif singulier des noms en -us de la 2e déclinaison est en -e : domine (« ô maître »)."),
 q(12,"moyen","mythologie","Quelle déesse est la déesse de la sagesse et protectrice d'Athènes ?",
   ["Héra","Aphrodite","Athéna","Artémis"],2,
   "Athéna (Minerve chez les Romains), déesse de la sagesse, protège la cité d'Athènes."),
])

# ---------- 04 quatrieme ----------
FILES[4] = ("quatrieme", [
 q(1,"moyen","declinaison-2","Quel est le nominatif-accusatif singulier du neutre « bellum » ?",
   ["bellum","belli","bello","bella"],0,
   "Pour un neutre de la 2e déclinaison, nominatif = accusatif : bellum au singulier."),
 q(2,"moyen","declinaison-2","Quel est le nominatif-accusatif pluriel du neutre « bellum » ?",
   ["belli","bella","bellorum","bellis"],1,
   "Le pluriel neutre (nominatif = accusatif) se termine en -a : bella."),
 q(3,"moyen","conjugaison-amo","Quelle est la forme de « amo » à la 1re personne du pluriel au présent ?",
   ["amat","amamus","amatis","amant"],1,
   "« nous aimons » se dit « amamus »."),
 q(4,"moyen","cas-fonction","En latin, quel cas exprime le complément d'attribution (COI) ?",
   ["L'accusatif","Le datif","L'ablatif","Le génitif"],1,
   "Le datif exprime l'attribution, souvent traduit par « à » ou « pour »."),
 q(5,"moyen","vocabulaire","Que signifie le mot latin « via » ?",
   ["la maison","la route/voie","la porte","le mur"],1,
   "« Via » signifie « la route, la voie » (cf. la Via Appia, viaduc)."),
 q(6,"moyen","alphabet-grec","Comment se nomme la lettre grecque « ω » ?",
   ["omicron","oméga","upsilon","phi"],1,
   "La lettre « ω » se nomme « oméga » ; c'est la dernière de l'alphabet grec."),
 q(7,"moyen","mythologie","Quel monstre au corps de taureau vivait dans le Labyrinthe de Crète ?",
   ["la Méduse","le Minotaure","le Cyclope","la Chimère"],1,
   "Le Minotaure, mi-homme mi-taureau, vivait dans le Labyrinthe et fut tué par Thésée."),
 q(8,"moyen","civilisation","Que désigne le sigle « SPQR » sur les enseignes romaines ?",
   ["Le Sénat et le Peuple romain","La République de Rome","Les sept rois de Rome","Le pouvoir des consuls"],0,
   "SPQR = Senatus Populusque Romanus, « le Sénat et le Peuple romain »."),
 q(9,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 3e personne du singulier à l'imparfait ?",
   ["est","erat","erit","erant"],1,
   "« il était » se dit « erat » (imparfait de sum)."),
 q(10,"moyen","vocabulaire","Que signifie le mot latin « liber » ?",
   ["libre seulement","le livre","la lettre","la page"],1,
   "« Liber » (2e décl.) signifie « le livre » (cf. librairie, libraire)."),
 q(11,"difficile","declinaison-2","Quel est le génitif pluriel de « bellum » ?",
   ["bella","bellis","bellorum","bellos"],2,
   "Le génitif pluriel de la 2e déclinaison est en -orum : bellorum (« des guerres »)."),
 q(12,"moyen","mythologie","Quel dieu romain est le messager des dieux, aux sandales ailées ?",
   ["Mars","Vulcain","Mercure","Bacchus"],2,
   "Mercure (Hermès chez les Grecs) est le messager des dieux."),
])

# ---------- 05 troisieme ----------
FILES[5] = ("troisieme", [
 q(1,"moyen","declinaison-3","Quel est le génitif singulier de « rex » (3e déclinaison) ?",
   ["rex","regis","regi","regem"],1,
   "Le génitif singulier de « rex » est « regis » ; le radical est reg-."),
 q(2,"moyen","declinaison-3","Quel est l'accusatif singulier de « rex » ?",
   ["rex","regis","regem","rege"],2,
   "L'accusatif singulier de la 3e déclinaison est en -em : regem."),
 q(3,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 1re personne du singulier au futur ?",
   ["sum","eram","ero","sim"],2,
   "Le futur de sum : ero, eris, erit, erimus, eritis, erunt. « je serai » = ero."),
 q(4,"moyen","cas-fonction","En latin, quel cas exprime souvent le complément circonstanciel de moyen ?",
   ["Le nominatif","L'accusatif","L'ablatif","Le vocatif"],2,
   "L'ablatif exprime notamment le moyen, la manière, le lieu (d'où l'on vient)."),
 q(5,"moyen","vocabulaire","Que signifie le mot latin « pax » ?",
   ["la guerre","la paix","la loi","la force"],1,
   "« Pax » signifie « la paix » (génitif : pacis ; cf. la Pax Romana)."),
 q(6,"moyen","alphabet-grec","Combien de lettres compte l'alphabet grec ?",
   ["21","23","24","26"],2,
   "L'alphabet grec compte 24 lettres, d'alpha (α) à oméga (ω)."),
 q(7,"moyen","mythologie","Quel héros a vaincu la Gorgone Méduse ?",
   ["Persée","Jason","Œdipe","Bellérophon"],0,
   "Persée décapita Méduse en utilisant son bouclier comme miroir."),
 q(8,"moyen","civilisation","Qui fut le premier empereur romain ?",
   ["Jules César","Auguste","Néron","Trajan"],1,
   "Auguste (Octave) devient le premier empereur romain en 27 av. J.-C."),
 q(9,"moyen","declinaison-3","Quel est le nominatif pluriel de « rex » ?",
   ["reges","regum","regibus","regis"],0,
   "Le nominatif pluriel de la 3e déclinaison est en -es : reges."),
 q(10,"moyen","vocabulaire","Que signifie le mot latin « vita » ?",
   ["la mort","la vie","la santé","le temps"],1,
   "« Vita » signifie « la vie » (cf. vital, vitalité) ; la mort se dit « mors »."),
 q(11,"difficile","declinaison-3","Quel est le datif pluriel de « rex » ?",
   ["reges","regum","regibus","regi"],2,
   "Le datif (et l'ablatif) pluriel de la 3e déclinaison est en -ibus : regibus. (Le génitif pluriel est regum.)"),
 q(12,"moyen","civilisation","Comment appelait-on à Rome le grand ouvrage qui amenait l'eau à la ville ?",
   ["le forum","l'aqueduc","la basilique","le cirque"],1,
   "L'aqueduc acheminait l'eau vers la ville, parfois sur de longues distances."),
])

# ---------- 06 seconde ----------
FILES[6] = ("seconde", [
 q(1,"moyen","conjugaison-amo","Quelle est la forme de « amo » à la 3e personne du singulier à l'imparfait ?",
   ["amat","amabat","amavit","amabit"],1,
   "L'imparfait d'amo se forme avec -ba- : amabam, amabas, amabat... « il aimait » = amabat."),
 q(2,"moyen","conjugaison-amo","Quelle est la forme de « amo » à la 3e personne du singulier au futur simple ?",
   ["amabat","amat","amabit","amavit"],2,
   "Le futur des 1re/2e conjugaisons se forme avec -bi- : amabo, amabis, amabit..."),
 q(3,"moyen","declinaison-3","Quel est le génitif pluriel de « rex » ?",
   ["reges","regibus","regum","regorum"],2,
   "Le génitif pluriel de la 3e déclinaison est en -um : regum."),
 q(4,"moyen","cas-fonction","Quelle est la fonction principale du vocatif en latin ?",
   ["Le sujet","L'apostrophe (interpeller quelqu'un)","Le COD","La possession"],1,
   "Le vocatif sert à interpeller ou à s'adresser à quelqu'un (« ô maître ! »)."),
 q(5,"moyen","vocabulaire-grec","Que signifie le mot grec « ἄνθρωπος » (anthrôpos) ?",
   ["le dieu","l'être humain","la cité","la parole"],1,
   "« Anthrôpos » désigne l'être humain, l'homme (cf. anthropologie)."),
 q(6,"moyen","alphabet-grec","Comment se nomme la lettre grecque « θ » ?",
   ["thêta","phi","psi","khi"],0,
   "La lettre « θ » se nomme « thêta » (son proche de [th])."),
 q(7,"moyen","mythologie","Dans l'Iliade, quel héros grec est le personnage central de la colère ?",
   ["Ulysse","Hector","Achille","Agamemnon"],2,
   "L'Iliade s'ouvre sur « la colère d'Achille » ; c'est le héros central du poème."),
 q(8,"moyen","civilisation","Que désigne le mot latin « domus » ?",
   ["un immeuble collectif","une maison de ville (aristocratique)","un temple","une boutique"],1,
   "La « domus » est la maison urbaine des familles aisées ; l'« insula » est l'immeuble collectif."),
 q(9,"moyen","litterature","Qui est l'auteur de l'Énéide, épopée sur les origines de Rome ?",
   ["Virgile","Cicéron","Ovide","Horace"],0,
   "L'Énéide est l'œuvre du poète Virgile, qui raconte le voyage d'Énée jusqu'en Italie."),
 q(10,"moyen","vocabulaire","Que signifie le mot latin « urbs » ?",
   ["la campagne","la ville","le champ","la province"],1,
   "« Urbs » signifie « la ville » (cf. urbain) ; par excellence, l'Urbs désigne Rome."),
 q(11,"difficile","conjugaison-amo","Quelle est la forme de « amo » à la 1re personne du singulier au parfait ?",
   ["amabam","amo","amavi","amabo"],2,
   "Le parfait d'amo est « amavi » (« j'ai aimé / j'aimai »)."),
 q(12,"moyen","mythologie","Quel Titan a donné le feu aux hommes malgré l'interdiction de Zeus ?",
   ["Atlas","Cronos","Prométhée","Océan"],2,
   "Prométhée déroba le feu pour le donner aux hommes et fut châtié par Zeus."),
])

# ---------- 07 seconde ----------
FILES[7] = ("seconde", [
 q(1,"moyen","vocabulaire-grec","Que signifie le mot grec « λόγος » (logos) ?",
   ["la parole, la raison","la guerre","la cité","le corps"],0,
   "« Logos » signifie la parole, le discours, la raison (cf. logique, -logie)."),
 q(2,"moyen","vocabulaire-grec","Que signifie le mot grec « πόλις » (polis) ?",
   ["la maison","la cité","le peuple","la loi"],1,
   "« Polis » désigne la cité (cf. politique, métropole)."),
 q(3,"moyen","alphabet-grec","Comment se nomme la lettre grecque « λ » ?",
   ["lambda","mu","nu","rho"],0,
   "La lettre « λ » se nomme « lambda » et correspond au son [l]."),
 q(4,"moyen","cas-fonction","En latin, une expression comme « in urbe » (« dans la ville ») met le nom à quel cas ?",
   ["Nominatif","Accusatif","Ablatif","Génitif"],2,
   "Le complément de lieu où l'on est, introduit par « in », se met à l'ablatif : in urbe."),
 q(5,"moyen","conjugaison-sum","Quelle est la forme de « sum » à la 3e personne du pluriel à l'imparfait ?",
   ["sunt","erant","erunt","erat"],1,
   "« ils étaient » se dit « erant » (imparfait de sum)."),
 q(6,"moyen","mythologie","Quel héros a affronté le Sphinx en résolvant son énigme ?",
   ["Thésée","Œdipe","Persée","Jason"],1,
   "Œdipe résout l'énigme du Sphinx de Thèbes."),
 q(7,"moyen","civilisation","À Rome, combien de consuls dirigeaient la République chaque année ?",
   ["un","deux","trois","dix"],1,
   "La République romaine était dirigée par deux consuls élus pour un an."),
 q(8,"moyen","litterature","Quel philosophe grec, maître de Platon, fut condamné à boire la ciguë ?",
   ["Aristote","Socrate","Épicure","Pythagore"],1,
   "Socrate, maître de Platon, fut condamné à mort à Athènes et but la ciguë."),
 q(9,"moyen","vocabulaire","Que signifie le verbe latin « videre » ?",
   ["entendre","voir","parler","venir"],1,
   "« Videre » signifie « voir » (cf. vision, vidéo, évident)."),
 q(10,"difficile","declinaison-1","Quel est le datif/ablatif pluriel de « rosa » ?",
   ["rosae","rosas","rosis","rosarum"],2,
   "Le datif et l'ablatif pluriels de la 1re déclinaison sont en -is : rosis."),
 q(11,"moyen","mythologie","Dans l'Odyssée, quel héros met dix ans à rentrer à Ithaque ?",
   ["Ulysse","Ménélas","Nestor","Ajax"],0,
   "L'Odyssée raconte le retour d'Ulysse (Odysseus) vers son île d'Ithaque."),
 q(12,"moyen","civilisation","Quel vêtement, drapé et blanc, symbolisait la citoyenneté romaine ?",
   ["la tunique","la toge","le péplos","la chlamyde"],1,
   "La toge, portée par les citoyens romains, était le symbole de la citoyenneté."),
])

# ---------- 08 premiere ----------
FILES[8] = ("premiere", [
 q(1,"difficile","syntaxe-latin","Dans « Marcus rosam puellae dat », à quelle fonction correspond « puellae » ?",
   ["Sujet","COD","Complément d'attribution (COI)","Complément du nom"],2,
   "« puellae » est ici au datif et exprime l'attribution : Marc donne une rose à la jeune fille."),
 q(2,"difficile","syntaxe-latin","Dans « Marcus rosam puellae dat », quel mot est le COD ?",
   ["Marcus","rosam","puellae","dat"],1,
   "« rosam » est à l'accusatif : c'est le COD (« une rose »)."),
 q(3,"difficile","conjugaison","Quelle est la traduction de « amabant » ?",
   ["ils aiment","ils aimeront","ils aimaient","ils ont aimé"],2,
   "« amabant » est l'imparfait 3e pers. pluriel : « ils aimaient »."),
 q(4,"difficile","proposition-infinitive","Dans une proposition infinitive, le sujet de l'infinitif se met à quel cas ?",
   ["Au nominatif","À l'accusatif","Au datif","Au génitif"],1,
   "Dans la proposition infinitive, le sujet de l'infinitif est à l'accusatif (ex. « scio Marcum venire »)."),
 q(5,"moyen","litterature","Quel orateur romain est célèbre pour ses discours contre Catilina ?",
   ["Sénèque","Cicéron","Tacite","Tite-Live"],1,
   "Cicéron prononça les Catilinaires contre la conjuration de Catilina en 63 av. J.-C."),
 q(6,"difficile","vocabulaire-grec","Que signifie le mot grec « δῆμος » (dêmos) ?",
   ["le roi","le peuple","la guerre","la loi"],1,
   "« Dêmos » signifie « le peuple » (cf. démocratie : le pouvoir du peuple)."),
 q(7,"moyen","civilisation","Quel régime politique est né à Athènes au Ve siècle av. J.-C. ?",
   ["la monarchie","la démocratie","la tyrannie","l'oligarchie"],1,
   "Athènes développe la démocratie, où les citoyens participent aux décisions."),
 q(8,"difficile","conjugaison-sum","Quelle est la traduction de « erimus » ?",
   ["nous étions","nous sommes","nous serons","nous fûmes"],2,
   "« erimus » est le futur 1re pers. pluriel de sum : « nous serons »."),
 q(9,"moyen","mythologie","Quelle boîte, ouverte par curiosité, libéra tous les maux sur l'humanité ?",
   ["la boîte de Pandore","la corne d'abondance","le tonneau des Danaïdes","le bouclier d'Achille"],0,
   "Pandore ouvrit la jarre (boîte) qui répandit les maux, ne laissant que l'espérance."),
 q(10,"difficile","cas-fonction","Le complément d'agent (avec un verbe passif) se construit avec « a/ab » et quel cas ?",
   ["Le nominatif","L'accusatif","L'ablatif","Le datif"],2,
   "Le complément d'agent d'un verbe passif se met à l'ablatif, précédé de « a/ab » pour une personne."),
 q(11,"moyen","civilisation","Qui fut assassiné aux ides de mars 44 av. J.-C. au Sénat ?",
   ["Auguste","Pompée","Jules César","Brutus"],2,
   "Jules César fut assassiné aux ides de mars (15 mars) 44 av. J.-C."),
 q(12,"difficile","vocabulaire","Que signifie le verbe latin « ferre » ?",
   ["faire","porter","dire","pouvoir"],1,
   "« Ferre » signifie « porter, supporter » (verbe irrégulier ; cf. offrir, transférer)."),
])

# ---------- 09 premiere ----------
FILES[9] = ("premiere", [
 q(1,"difficile","syntaxe-latin","Dans « rex urbem servat » (« le roi protège la ville »), quel mot est le sujet ?",
   ["rex","urbem","servat","urbs"],0,
   "« rex » est au nominatif : c'est le sujet du verbe servat."),
 q(2,"difficile","ablatif-absolu","L'ablatif absolu est une proposition construite avec quels éléments ?",
   ["Un nom et un verbe conjugué","Un nom et un participe, tous deux à l'ablatif","Un accusatif et un infinitif","Un nominatif et un datif"],1,
   "L'ablatif absolu associe un nom et un participe, tous deux à l'ablatif (ex. « urbe capta »)."),
 q(3,"moyen","litterature","Quel poète latin est l'auteur des Métamorphoses ?",
   ["Virgile","Ovide","Horace","Lucrèce"],1,
   "Les Métamorphoses sont l'œuvre d'Ovide, recueil de récits mythologiques."),
 q(4,"difficile","vocabulaire-grec","Que signifie le mot grec « σοφία » (sophia) ?",
   ["la force","la sagesse","la beauté","la richesse"],1,
   "« Sophia » signifie la sagesse (cf. philosophie : l'amour de la sagesse)."),
 q(5,"difficile","conjugaison","Quelle est la traduction de « amaverunt » ?",
   ["ils aimaient","ils aimeront","ils ont aimé / ils aimèrent","ils aiment"],2,
   "« amaverunt » est le parfait 3e pers. pluriel : « ils ont aimé / ils aimèrent »."),
 q(6,"moyen","civilisation","Quelles sont les épreuves sportives grecques organisées tous les quatre ans à Olympie ?",
   ["les Panathénées","les Jeux Olympiques","les Dionysies","les Saturnales"],1,
   "Les Jeux Olympiques se tenaient tous les quatre ans à Olympie en l'honneur de Zeus."),
 q(7,"difficile","cas-fonction","Dans « liber magistri » (« le livre du maître »), à quel cas est « magistri » ?",
   ["Nominatif","Génitif","Datif","Accusatif"],1,
   "« magistri » est au génitif et exprime le complément du nom (la possession)."),
 q(8,"moyen","mythologie","Quel personnage s'approcha trop du soleil avec des ailes de cire ?",
   ["Dédale","Icare","Phaéton","Bellérophon"],1,
   "Icare, fils de Dédale, s'approcha du soleil : la cire fondit et il tomba dans la mer."),
 q(9,"difficile","conjugaison-sum","Quelle est la traduction de « erat » ?",
   ["il est","il était","il sera","il fut"],1,
   "« erat » est l'imparfait 3e pers. singulier de sum : « il/elle était »."),
 q(10,"moyen","litterature","Quel historien romain a écrit « Ab Urbe condita », une histoire de Rome ?",
   ["Tacite","Tite-Live","Salluste","Suétone"],1,
   "Tite-Live est l'auteur d'« Ab Urbe condita », histoire de Rome depuis sa fondation."),
 q(11,"difficile","vocabulaire","Que signifie l'adjectif latin « magnus » ?",
   ["petit","grand","mauvais","nouveau"],1,
   "« Magnus » signifie « grand » (cf. magnifique, magnat) ; son contraire est « parvus »."),
 q(12,"moyen","civilisation","Comment nommait-on le chef de famille tout-puissant dans la société romaine ?",
   ["le patronus","le pater familias","le princeps","le censor"],1,
   "Le « pater familias » détenait l'autorité (patria potestas) sur toute la famille."),
])

# ---------- 10 terminale ----------
FILES[10] = ("terminale", [
 q(1,"difficile","syntaxe-latin","Dans « urbe capta, hostes discesserunt », comment traduire l'ablatif absolu « urbe capta » ?",
   ["parce que la ville prend","la ville ayant été prise","la ville prendra","pour prendre la ville"],1,
   "« urbe capta » est un ablatif absolu à valeur temporelle/causale : « la ville ayant été prise »."),
 q(2,"difficile","subjonctif","Le subjonctif imparfait de « sum » à la 3e personne du singulier est :",
   ["sit","esset","erat","fuisset"],1,
   "Le subjonctif imparfait de sum : essem, esses, esset... « esset » = 3e pers. singulier."),
 q(3,"difficile","conjugaison","Quelle est la traduction du plus-que-parfait « amaverat » ?",
   ["il aimait","il avait aimé","il aura aimé","il aima"],1,
   "« amaverat » est le plus-que-parfait 3e pers. singulier : « il avait aimé »."),
 q(4,"difficile","vocabulaire-grec","Que signifie le mot grec « βίος » (bios) ?",
   ["la mort","la vie","le temps","la nature"],1,
   "« Bios » signifie « la vie » (cf. biologie, biographie)."),
 q(5,"moyen","litterature","Quel philosophe grec a fondé le Lycée et fut le précepteur d'Alexandre le Grand ?",
   ["Platon","Aristote","Épicure","Zénon"],1,
   "Aristote, élève de Platon, fonda le Lycée et fut le précepteur d'Alexandre le Grand."),
 q(6,"difficile","gerondif-adjectif-verbal","En latin, le gérondif sert principalement à :",
   ["conjuguer le passif","décliner l'infinitif (nom verbal)","former le futur","marquer le pluriel"],1,
   "Le gérondif est un nom verbal qui permet de décliner l'idée exprimée par le verbe (ars amandi, etc.)."),
 q(7,"moyen","civilisation","Quel empereur romain a fait de l'édit de 313 (Milan) un tournant pour les chrétiens ?",
   ["Néron","Constantin","Dioclétien","Trajan"],1,
   "Constantin, par l'édit de Milan (313), accorda la liberté de culte aux chrétiens."),
 q(8,"difficile","cas-fonction","Le « datif de possession » (ex. « est mihi liber ») se traduit littéralement par :",
   ["je lis un livre","il y a pour moi un livre = j'ai un livre","le livre est à moi de force","je donne un livre"],1,
   "Le datif de possession avec « esse » : « est mihi liber » = « il y a pour moi un livre », c'est-à-dire « j'ai un livre »."),
 q(9,"moyen","mythologie","Quel chien à trois têtes garde l'entrée des Enfers dans la mythologie grecque ?",
   ["Cerbère","Argos","Orthros","Scylla"],0,
   "Cerbère, chien à trois têtes, garde l'entrée du royaume d'Hadès (les Enfers)."),
 q(10,"difficile","conjugaison","Quelle est la traduction de « amabor » (voix passive) ?",
   ["j'aime","j'aimais","je serai aimé(e)","j'ai été aimé(e)"],2,
   "« amabor » est le futur passif 1re pers. singulier : « je serai aimé(e) »."),
 q(11,"moyen","litterature","Quel poète latin a écrit le « De rerum natura », exposé de la philosophie épicurienne ?",
   ["Lucrèce","Catulle","Properce","Martial"],0,
   "Lucrèce expose la physique et la morale épicuriennes dans le « De rerum natura »."),
 q(12,"difficile","vocabulaire-grec","Que signifie le mot grec « φῶς » (phôs) ?",
   ["l'ombre","la lumière","le son","la voix"],1,
   "« Phôs » signifie « la lumière » (cf. photographie, phosphore)."),
])

import random
def rebalance(questions, seed):
    # target positions: each of 0..3 exactly 3 times, shuffled deterministically
    targets = [0,1,2,3]*3
    rnd = random.Random(seed)
    rnd.shuffle(targets)
    for qq, t in zip(questions, targets):
        r = qq["reponse"]
        correct = qq["choix"][r]
        others = [c for i,c in enumerate(qq["choix"]) if i != r]
        newchoix = list(others)
        newchoix.insert(t, correct)
        qq["choix"] = newchoix
        qq["reponse"] = t
    return questions

for nn,(niveau,questions) in FILES.items():
    questions = rebalance(questions, nn)
    assert [x["id"] for x in questions] == list(range(1,13)), nn
    data = {
        "id": f"bb-langues-anciennes-{nn:02d}",
        "titre": f"Bac blanc — Langues anciennes (n° {nn:02d})",
        "examen": "Bac blanc",
        "niveau": niveau,
        "matiere": "langues-anciennes",
        "statut": "brouillon",
        "relu_par": None,
        "consigne": "Une seule réponse correcte par question. Latin, grec et civilisation antique.",
        "questions": questions,
    }
    path = os.path.join(OUT, f"bb-langues-anciennes-{nn:02d}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    # answer distribution report
    dist = {}
    for x in questions:
        dist[x["reponse"]] = dist.get(x["reponse"],0)+1
    print(nn, niveau, "positions:", dict(sorted(dist.items())))
print("written")
