#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json, os

OUT = "/tmp/kamal-campus/quiz"
os.makedirs(OUT, exist_ok=True)

# Helper: q(difficulte, notion, enonce, choix, reponse, explication)
def q(i, d, n, e, ch, r, ex):
    assert len(ch) == 4 and len(set(ch)) == 4, (i, ch)
    assert 0 <= r < 4
    assert ex
    return {"id": i, "difficulte": d, "notion": n, "enonce": e,
            "choix": ch, "reponse": r, "explication": ex}

FILES = {}

# ---------------------------------------------------------------------------
# 01 — SECONDE — Marché, production, consommation
# ---------------------------------------------------------------------------
FILES["01"] = ("seconde", [
    q(1, "facile", "pib",
      "Que mesure principalement le PIB d'un pays ?",
      ["La richesse (valeur ajoutée) produite sur le territoire en un an",
       "Le nombre total d'habitants du pays",
       "La quantité de monnaie en circulation",
       "Le montant total de l'épargne des ménages"],
      0,
      "Le PIB est la somme des valeurs ajoutées des unités productives résidentes sur une période, généralement une année."),
    q(2, "facile", "valeur-ajoutee",
      "Une boulangerie achète 30 000 euros de farine et vend 100 000 euros de pain. Quelle est sa valeur ajoutée ?",
      ["130 000 euros", "70 000 euros", "100 000 euros", "30 000 euros"],
      1,
      "Valeur ajoutée = production (100 000) - consommations intermédiaires (30 000) = 70 000 euros."),
    q(3, "facile", "offre-demande",
      "Sur un marché concurrentiel, si la demande d'un bien augmente et que l'offre reste stable, que se passe-t-il pour le prix ?",
      ["Il diminue", "Il reste identique", "Il augmente", "Il devient nul"],
      2,
      "Une demande qui augmente face à une offre inchangée crée une tension qui pousse le prix à la hausse."),
    q(4, "facile", "agents-economiques",
      "Quel agent économique a pour fonction principale de produire des biens et des services marchands ?",
      ["Les ménages", "Les administrations publiques", "Les associations", "Les entreprises"],
      3,
      "Les entreprises (sociétés non financières) ont pour fonction principale la production de biens et services marchands."),
    q(5, "facile", "revenu-disponible",
      "Le revenu disponible d'un ménage correspond aux revenus :",
      ["après versement des impôts directs et perception des prestations sociales",
       "avant tout prélèvement, c'est-à-dire le salaire brut",
       "uniquement issus du patrimoine (loyers, dividendes)",
       "égaux à la totalité de sa consommation annuelle"],
      0,
      "Le revenu disponible = revenus primaires + prestations sociales - prélèvements obligatoires directs. Il peut être consommé ou épargné."),
    q(6, "moyen", "consommation-epargne",
      "Un ménage dispose de 2 500 euros de revenu disponible et en consomme 2 000. Quel est son taux d'épargne ?",
      ["25 %", "80 %", "20 %", "5 %"],
      2,
      "Épargne = 2 500 - 2 000 = 500. Taux d'épargne = 500 / 2 500 = 0,20 soit 20 %."),
    q(7, "facile", "facteurs-production",
      "Le travail et le capital sont désignés en économie comme :",
      ["des consommations intermédiaires", "des facteurs de production",
       "des biens de consommation finale", "des prélèvements obligatoires"],
      1,
      "Le travail et le capital (technique) sont les deux grands facteurs de production combinés pour produire."),
    q(8, "moyen", "taux-de-variation",
      "Le chiffre d'affaires d'une entreprise passe de 200 000 à 250 000 euros. Quel est son taux de variation ?",
      ["50 %", "20 %", "25 %", "5 %"],
      2,
      "Taux de variation = (250 000 - 200 000) / 200 000 = 50 000 / 200 000 = 0,25 soit 25 %."),
    q(9, "facile", "marche",
      "Un marché, au sens économique, est avant tout :",
      ["un lieu couvert où l'on vend des fruits et légumes",
       "un service de l'administration fiscale",
       "un document comptable de l'entreprise",
       "le lieu, réel ou fictif, de rencontre entre offre et demande"],
      3,
      "En économie, le marché est le lieu (physique ou non) de rencontre entre offreurs et demandeurs, d'où émerge un prix."),
    q(10, "facile", "biens-services",
      "Une coupe de cheveux chez le coiffeur est :",
      ["un service marchand", "un bien durable",
       "une consommation intermédiaire", "un bien non marchand"],
      0,
      "Une prestation immatérielle vendue à un prix couvrant son coût est un service marchand."),
    q(11, "moyen", "productivite",
      "La productivité du travail se calcule en rapportant :",
      ["le capital au nombre d'entreprises",
       "la production à la quantité de travail utilisée",
       "les salaires au chiffre d'affaires",
       "l'épargne au revenu disponible"],
      1,
      "La productivité du travail = production / quantité de facteur travail (par exemple production par heure travaillée)."),
    q(12, "moyen", "offre-demande",
      "Sur un marché, une baisse du prix d'un bien entraîne généralement, toutes choses égales par ailleurs :",
      ["une baisse de la quantité demandée",
       "une hausse de la quantité offerte par les producteurs",
       "une disparition du marché",
       "une hausse de la quantité demandée par les consommateurs"],
      3,
      "Selon la loi de la demande, quand le prix baisse, la quantité demandée augmente (l'offre, elle, diminue)."),
])

# ---------------------------------------------------------------------------
# 02 — SECONDE — Monnaie, entreprises, socialisation
# ---------------------------------------------------------------------------
FILES["02"] = ("seconde", [
    q(1, "facile", "monnaie",
      "Parmi ces fonctions, laquelle N'EST PAS une fonction de la monnaie ?",
      ["Intermédiaire des échanges", "Unité de compte",
       "Réserve de valeur", "Production de biens matériels"],
      3,
      "La monnaie sert d'intermédiaire des échanges, d'unité de compte et de réserve de valeur, mais elle ne produit rien par elle-même."),
    q(2, "facile", "troc",
      "Le principal inconvénient du troc que la monnaie permet de résoudre est :",
      ["la nécessité d'une double coïncidence des besoins",
       "l'existence des impôts",
       "la présence de plusieurs vendeurs",
       "la variété des biens produits"],
      0,
      "Le troc suppose que chacun désire exactement ce que l'autre propose (double coïncidence des besoins) ; la monnaie lève cette contrainte."),
    q(3, "facile", "socialisation",
      "La socialisation désigne le processus par lequel un individu :",
      ["obtient un emploi rémunéré",
       "paie ses impôts à l'État",
       "intériorise les normes et les valeurs de la société",
       "crée une entreprise"],
      2,
      "La socialisation est le processus d'apprentissage et d'intériorisation des normes, valeurs et rôles sociaux."),
    q(4, "facile", "instances-socialisation",
      "Laquelle de ces instances est un agent de socialisation primaire pour l'enfant ?",
      ["L'entreprise", "Le syndicat professionnel",
       "Le parti politique", "La famille"],
      3,
      "La famille est l'instance de socialisation primaire, la première à transmettre normes et valeurs à l'enfant."),
    q(5, "moyen", "entreprise",
      "Le profit d'une entreprise correspond, en simplifiant, à :",
      ["la différence entre ses recettes et ses coûts",
       "la totalité de son chiffre d'affaires",
       "le montant de ses salaires versés",
       "la valeur de ses stocks de marchandises"],
      0,
      "Le profit (ou bénéfice) est ce qui reste des recettes une fois retranchés l'ensemble des coûts."),
    q(6, "moyen", "creation-monnaie",
      "Aujourd'hui, l'essentiel de la monnaie en circulation est créé :",
      ["par l'impression de billets par l'État",
       "par les crédits accordés par les banques commerciales",
       "par l'épargne des ménages placée en Bourse",
       "par les échanges de biens entre entreprises"],
      1,
      "La majeure partie de la monnaie est scripturale : « les crédits font les dépôts », les banques créent de la monnaie en accordant des prêts."),
    q(7, "facile", "normes-valeurs",
      "« La ponctualité » relève plutôt d'une norme, tandis que « le respect de la vie » relève plutôt :",
      ["d'une valeur", "d'un impôt", "d'un salaire", "d'un contrat de travail"],
      0,
      "Les valeurs sont des idéaux (le respect de la vie) ; les normes sont des règles concrètes de conduite (être ponctuel) qui découlent des valeurs."),
    q(8, "moyen", "taux-de-variation",
      "Le nombre d'adhérents d'un club passe de 80 à 60. Quel est le taux de variation ?",
      ["-20 %", "-33 %", "-25 %", "+25 %"],
      2,
      "Taux = (60 - 80) / 80 = -20 / 80 = -0,25 soit -25 %."),
    q(9, "facile", "diversite-entreprises",
      "Une entreprise individuelle se distingue d'une société par actions car :",
      ["elle ne peut pas embaucher de salariés",
       "elle appartient à une seule personne, sans distinction juridique nette avec son patrimoine",
       "elle ne paie jamais d'impôts",
       "elle appartient obligatoirement à l'État"],
      1,
      "Dans l'entreprise individuelle, l'entrepreneur et l'entreprise ne forment qu'une seule personne juridique, contrairement à la société."),
    q(10, "facile", "socialisation-secondaire",
      "L'apprentissage des règles d'un métier lors de son premier emploi relève de la socialisation :",
      ["primaire", "familiale", "génétique", "secondaire"],
      3,
      "La socialisation secondaire intervient à l'âge adulte, notamment dans le monde du travail, et complète la socialisation primaire."),
    q(11, "moyen", "banque-centrale",
      "Quel est le rôle principal de la Banque centrale européenne (BCE) ?",
      ["Fixer le salaire minimum en Europe",
       "Veiller à la stabilité des prix et émettre l'euro",
       "Voter le budget de la France",
       "Employer directement tous les fonctionnaires"],
      1,
      "La BCE a pour mission principale la stabilité des prix (maîtrise de l'inflation) et le monopole d'émission de l'euro."),
    q(12, "moyen", "consommation",
      "Un bien durable se distingue d'un bien non durable par le fait qu'il :",
      ["se consomme en une seule utilisation",
       "n'a aucune valeur marchande",
       "est utilisé plusieurs fois sur une longue période",
       "est toujours gratuit"],
      2,
      "Un bien durable (voiture, réfrigérateur) sert à de multiples usages sur la durée, contrairement à un bien non durable (aliment)."),
])

# ---------------------------------------------------------------------------
# 03 — SECONDE — Groupes sociaux, individu, marché du travail (bases)
# ---------------------------------------------------------------------------
FILES["03"] = ("seconde", [
    q(1, "facile", "groupe-social",
      "Un ensemble d'individus qui interagissent, ont conscience d'appartenir au même ensemble et partagent des buts communs forme :",
      ["un groupe social", "une catégorie statistique",
       "une consommation intermédiaire", "un prélèvement obligatoire"],
      0,
      "Un groupe social suppose interactions, conscience d'appartenance et objectifs communs, à la différence d'une simple catégorie statistique."),
    q(2, "facile", "groupe-primaire-secondaire",
      "La bande d'amis proches constitue typiquement :",
      ["un groupe secondaire de grande taille",
       "une administration publique",
       "un groupe primaire fondé sur des relations directes et affectives",
       "un marché financier"],
      2,
      "Un groupe primaire se caractérise par des relations directes, personnelles et affectives, comme une bande d'amis ou la famille."),
    q(3, "facile", "chomage",
      "Selon le Bureau international du travail (BIT), une personne est au chômage si elle :",
      ["est âgée de plus de 60 ans",
       "travaille à temps partiel",
       "gagne un revenu inférieur au SMIC",
       "est sans emploi, disponible et recherche activement un emploi"],
      3,
      "Au sens du BIT, un chômeur est une personne en âge de travailler, sans emploi, disponible et engagée dans une recherche active d'emploi."),
    q(4, "facile", "population-active",
      "La population active regroupe :",
      ["les personnes ayant un emploi et les chômeurs",
       "uniquement les personnes ayant un emploi",
       "l'ensemble des habitants du pays",
       "uniquement les retraités et les étudiants"],
      0,
      "La population active = actifs occupés (ayant un emploi) + chômeurs (sans emploi mais en recherche)."),
    q(5, "moyen", "taux-de-chomage",
      "Un pays compte 27 millions d'actifs dont 3 millions de chômeurs. Quel est le taux de chômage ?",
      ["11,1 %", "3 %", "27 %", "9 %"],
      0,
      "Taux de chômage = chômeurs / population active = 3 / 27 = 0,111 soit environ 11,1 %."),
    q(6, "facile", "controle-social",
      "Une amende pour excès de vitesse est un exemple de contrôle social :",
      ["informel", "formel", "génétique", "monétaire"],
      1,
      "Le contrôle social formel s'exerce par des institutions et des sanctions officielles (police, justice, amendes), à la différence des sanctions informelles (regards, moqueries)."),
    q(7, "facile", "socialisation-genre",
      "Offrir surtout des poupées aux filles et des voitures aux garçons illustre :",
      ["la création monétaire",
       "une socialisation différenciée selon le genre",
       "le calcul du PIB",
       "une consommation intermédiaire"],
      1,
      "Cet exemple montre une socialisation différenciée : les attentes et objets varient selon le sexe de l'enfant."),
    q(8, "moyen", "proportion",
      "Dans une classe de 30 élèves, 18 sont des filles. Quelle est la proportion de filles ?",
      ["30 %", "18 %", "60 %", "12 %"],
      2,
      "Proportion = 18 / 30 = 0,60 soit 60 %."),
    q(9, "facile", "salaire",
      "Le salaire est la rémunération :",
      ["du facteur travail", "du facteur capital",
       "des consommations intermédiaires", "des impôts locaux"],
      0,
      "Le salaire rémunère le facteur travail ; le capital est rémunéré par les intérêts, dividendes ou profits."),
    q(10, "facile", "categorie-sociale",
      "Les PCS (professions et catégories socioprofessionnelles) de l'INSEE servent à :",
      ["fixer le salaire minimum",
       "classer la population selon la profession et le statut",
       "calculer le taux d'inflation",
       "émettre la monnaie"],
      1,
      "Les PCS sont une nomenclature statistique qui classe les individus selon leur profession, leur statut et leur position sociale."),
    q(11, "moyen", "offre-demande",
      "Sur le marché du travail, l'offre de travail émane :",
      ["des entreprises qui cherchent à embaucher",
       "de l'État uniquement",
       "des travailleurs qui proposent leur force de travail",
       "des banques centrales"],
      2,
      "Sur le marché du travail, ce sont les travailleurs qui offrent leur travail ; les entreprises en expriment la demande."),
    q(12, "moyen", "reseaux-sociaux",
      "Un réseau social (au sens sociologique) désigne :",
      ["uniquement une application de smartphone",
       "un impôt sur les entreprises",
       "l'ensemble des relations qu'un individu entretient avec d'autres",
       "un type de contrat de travail"],
      2,
      "En sociologie, un réseau social est l'ensemble des liens et relations qu'un individu entretient, mobilisables comme ressources (capital social)."),
])

# ---------------------------------------------------------------------------
# 04 — PREMIERE — Marché concurrentiel, élasticité, défaillances
# ---------------------------------------------------------------------------
FILES["04"] = ("premiere", [
    q(1, "facile", "concurrence-pure-parfaite",
      "Parmi ces conditions, laquelle N'appartient PAS à la concurrence pure et parfaite ?",
      ["Atomicité du marché", "Homogénéité du produit",
       "Existence d'un monopole", "Libre entrée et sortie du marché"],
      2,
      "La CPP suppose atomicité, homogénéité, fluidité (libre entrée/sortie), transparence et mobilité des facteurs ; un monopole contredit l'atomicité."),
    q(2, "moyen", "elasticite-prix",
      "Le prix d'un bien augmente de 10 % et la quantité demandée baisse de 20 %. L'élasticité-prix de la demande vaut :",
      ["-2", "-0,5", "+2", "+0,5"],
      0,
      "Élasticité-prix = variation de la demande / variation du prix = (-20 %) / (+10 %) = -2. La demande est élastique."),
    q(3, "moyen", "elasticite-prix",
      "Une demande dite « inélastique » au prix se caractérise par une élasticité-prix :",
      ["supérieure à 1 en valeur absolue",
       "comprise entre 0 et 1 en valeur absolue",
       "toujours positive",
       "égale à l'infini"],
      1,
      "Quand l'élasticité-prix est comprise entre 0 et 1 (en valeur absolue), la demande varie peu face au prix : elle est inélastique (biens de première nécessité)."),
    q(4, "facile", "externalite",
      "Une usine qui pollue une rivière sans dédommager les riverains produit :",
      ["une externalité négative",
       "une externalité positive",
       "un bien public",
       "une consommation intermédiaire"],
      0,
      "Une externalité négative est un effet non compensé subi par des tiers ; ici la pollution est une externalité négative de production."),
    q(5, "facile", "externalite",
      "La recherche fondamentale dont les résultats profitent gratuitement à d'autres entreprises est un exemple d'externalité :",
      ["négative", "monétaire", "positive", "fiscale"],
      2,
      "Une externalité positive procure un bénéfice non facturé à des tiers ; la diffusion des connaissances en est un exemple classique."),
    q(6, "moyen", "pouvoir-marche",
      "Sur un marché en monopole, par rapport à la concurrence, l'entreprise tend à :",
      ["vendre plus en baissant fortement les prix",
       "fixer un prix plus élevé et vendre une quantité plus faible",
       "réaliser toujours des pertes",
       "perdre tout pouvoir sur le prix"],
      1,
      "Un monopole est « price maker » : il restreint les quantités pour fixer un prix plus élevé qu'en concurrence, ce qui accroît son profit."),
    q(7, "moyen", "asymetrie-information",
      "Sur le marché de l'occasion automobile, le vendeur en sait plus que l'acheteur sur l'état du véhicule. On parle :",
      ["de bien collectif", "d'atomicité",
       "d'asymétrie d'information", "d'externalité positive"],
      2,
      "Quand une partie dispose de plus d'informations que l'autre, il y a asymétrie d'information, source de défaillance du marché (sélection adverse)."),
    q(8, "moyen", "taxe-pigou",
      "Pour corriger une externalité négative comme la pollution, l'État peut :",
      ["supprimer la monnaie",
       "interdire toute production dans le pays",
       "instaurer une taxe faisant payer au pollueur le coût social",
       "augmenter le salaire minimum"],
      2,
      "Une taxe (dite pigouvienne) internalise l'externalité : elle fait supporter au pollueur le coût imposé à la société (principe pollueur-payeur)."),
    q(9, "facile", "surplus",
      "Le surplus du consommateur correspond à :",
      ["la différence entre le prix qu'il était prêt à payer et le prix effectivement payé",
       "le montant total de ses impôts",
       "le profit réalisé par le vendeur",
       "la quantité totale produite sur le marché"],
      0,
      "Le surplus du consommateur mesure le gain à l'échange : écart entre la disposition à payer et le prix payé."),
    q(10, "moyen", "bien-public",
      "L'éclairage public est souvent cité comme un bien public car il est :",
      ["rival et exclusif",
       "non rival et non exclusif",
       "produit uniquement par les entreprises privées",
       "réservé aux plus riches"],
      1,
      "Un bien public pur est non rival (l'usage de l'un ne prive pas l'autre) et non exclusif (on ne peut en écarter personne), d'où sa sous-production par le marché."),
    q(11, "moyen", "elasticite-revenu",
      "Un bien dont la consommation diminue lorsque le revenu augmente est un bien :",
      ["normal", "de luxe", "public", "inférieur"],
      3,
      "Un bien inférieur a une élasticité-revenu négative : quand le revenu augmente, sa consommation baisse (par exemple certains produits bas de gamme)."),
    q(12, "moyen", "equilibre-marche",
      "L'équilibre de marché est atteint lorsque :",
      ["l'offre est supérieure à la demande",
       "la quantité offerte est égale à la quantité demandée",
       "le prix est fixé par l'État",
       "la demande est nulle"],
      1,
      "À l'équilibre concurrentiel, le prix ajuste offre et demande de sorte que les quantités offerte et demandée sont égales."),
])

# ---------------------------------------------------------------------------
# 05 — PREMIERE — Monnaie, financement, création monétaire
# ---------------------------------------------------------------------------
FILES["05"] = ("premiere", [
    q(1, "facile", "creation-monnaie",
      "L'expression « les crédits font les dépôts » signifie que :",
      ["les banques prêtent uniquement l'épargne préexistante des ménages",
       "l'octroi d'un crédit bancaire crée de la monnaie nouvelle",
       "l'État imprime des billets pour financer les entreprises",
       "les dépôts des clients sont détruits par les crédits"],
      1,
      "Quand une banque accorde un crédit, elle inscrit une somme au compte de l'emprunteur : elle crée de la monnaie scripturale ex nihilo."),
    q(2, "moyen", "financement",
      "Le financement direct (externe) d'une entreprise correspond à :",
      ["un emprunt auprès d'une banque",
       "l'autofinancement par ses bénéfices",
       "l'émission d'actions ou d'obligations sur les marchés",
       "une subvention de la commune"],
      2,
      "Le financement direct se fait sur les marchés de capitaux (émission d'actions ou d'obligations), sans intermédiaire bancaire, contrairement au financement indirect."),
    q(3, "facile", "action-obligation",
      "Une obligation est :",
      ["un titre de propriété d'une part de l'entreprise",
       "un titre de créance donnant droit à un remboursement et à des intérêts",
       "une somme versée à l'État sous forme d'impôt",
       "une monnaie émise par la banque centrale"],
      1,
      "Une obligation est un titre de dette : le détenteur prête à l'émetteur et perçoit des intérêts, puis le remboursement, sans devenir propriétaire."),
    q(4, "facile", "action-obligation",
      "Détenir une action d'une société donne notamment droit :",
      ["à un salaire mensuel garanti",
       "au remboursement d'un prêt à échéance fixe",
       "à une part des bénéfices sous forme de dividendes",
       "à une exonération d'impôts"],
      2,
      "L'action est un titre de propriété : l'actionnaire peut recevoir des dividendes (part des bénéfices) et dispose d'un droit de vote."),
    q(5, "moyen", "taux-interet",
      "Toutes choses égales par ailleurs, une hausse des taux d'intérêt tend à :",
      ["encourager fortement l'investissement à crédit",
       "décourager l'emprunt et donc freiner l'investissement",
       "supprimer l'inflation immédiatement",
       "augmenter la quantité de monnaie créée par les crédits"],
      1,
      "Des taux plus élevés renchérissent le coût du crédit, ce qui décourage emprunts et investissements financés par la dette."),
    q(6, "moyen", "banque-centrale",
      "La banque centrale est souvent appelée « prêteur en dernier ressort » car elle :",
      ["prête aux ménages pour leur consommation",
       "fournit des liquidités aux banques pour éviter une crise de financement",
       "collecte l'impôt sur le revenu",
       "fixe le prix de tous les biens"],
      1,
      "En cas de tension, la banque centrale refinance les banques commerciales et leur fournit des liquidités : c'est le prêteur en dernier ressort."),
    q(7, "facile", "masse-monetaire",
      "La masse monétaire désigne :",
      ["la quantité de monnaie en circulation dans une économie",
       "le total des impôts collectés",
       "la valeur ajoutée des banques",
       "le nombre de billets détruits chaque année"],
      0,
      "La masse monétaire mesure l'ensemble des moyens de paiement (pièces, billets, dépôts) détenus par les agents non financiers."),
    q(8, "moyen", "taux-de-variation",
      "Un investissement rapporte 1 200 euros d'intérêts pour un placement de 30 000 euros sur un an. Quel est le taux d'intérêt annuel ?",
      ["12 %", "1,2 %", "4 %", "40 %"],
      2,
      "Taux = 1 200 / 30 000 = 0,04 soit 4 % par an."),
    q(9, "facile", "inflation",
      "L'inflation est définie comme :",
      ["une hausse ponctuelle du prix d'un seul bien",
       "une baisse générale et durable des prix",
       "une hausse générale et durable du niveau des prix",
       "une augmentation du nombre de chômeurs"],
      2,
      "L'inflation est la hausse générale, durable et auto-entretenue du niveau moyen des prix, mesurée par l'indice des prix à la consommation."),
    q(10, "moyen", "role-banques",
      "Les banques commerciales assurent l'intermédiation financière en :",
      ["collectant l'épargne et en accordant des crédits",
       "émettant l'euro à la place de la BCE",
       "votant le budget de l'État",
       "fixant le salaire minimum"],
      0,
      "L'intermédiation financière consiste à mettre en relation capacités et besoins de financement, en collectant l'épargne pour prêter."),
    q(11, "moyen", "financement-interne",
      "L'autofinancement d'une entreprise correspond à un financement :",
      ["externe direct", "externe indirect",
       "par emprunt obligataire", "interne, à partir de ses propres ressources"],
      3,
      "L'autofinancement est un financement interne : l'entreprise utilise ses bénéfices non distribués (épargne) pour financer ses projets."),
    q(12, "difficile", "creation-monnaie",
      "Lorsqu'un crédit bancaire est remboursé, du point de vue de la masse monétaire, il y a :",
      ["destruction de monnaie",
       "création de monnaie supplémentaire",
       "aucun effet sur la masse monétaire",
       "émission de nouveaux billets"],
      0,
      "Le remboursement d'un crédit détruit la monnaie créée lors de son octroi : la masse monétaire diminue d'autant."),
])

# ---------------------------------------------------------------------------
# 06 — PREMIERE — Socialisation, réseaux, opinion, science politique
# ---------------------------------------------------------------------------
FILES["06"] = ("premiere", [
    q(1, "facile", "socialisation-differenciee",
      "La socialisation différenciée selon le milieu social désigne le fait que :",
      ["tous les enfants reçoivent la même éducation",
       "les normes et pratiques transmises varient selon l'origine sociale",
       "la socialisation s'arrête à l'adolescence",
       "seule l'école socialise les individus"],
      1,
      "La socialisation est différenciée : les milieux sociaux transmettent des dispositions, des goûts et des pratiques distincts (Bourdieu, habitus)."),
    q(2, "moyen", "capital-social",
      "Le « capital social » d'un individu, au sens de la sociologie des réseaux, correspond :",
      ["à son épargne bancaire",
       "à ses diplômes et connaissances",
       "à l'ensemble des ressources tirées de son réseau de relations",
       "à son patrimoine immobilier"],
      2,
      "Le capital social désigne les ressources (informations, appuis, opportunités) qu'un individu peut mobiliser grâce à son réseau relationnel."),
    q(3, "moyen", "force-liens-faibles",
      "Selon Granovetter, pour trouver un emploi, les « liens faibles » sont souvent utiles car ils :",
      ["donnent accès à des informations nouvelles hors du cercle proche",
       "sont plus affectifs que les liens forts",
       "concernent uniquement la famille proche",
       "n'apportent aucune information"],
      0,
      "Les liens faibles (connaissances, relations éloignées) ouvrent sur d'autres réseaux et apportent des informations inédites : c'est « la force des liens faibles »."),
    q(4, "facile", "opinion-publique",
      "Un sondage d'opinion vise à :",
      ["mesurer la production nationale",
       "estimer l'opinion d'une population à partir d'un échantillon",
       "fixer le résultat officiel d'une élection",
       "calculer le taux d'inflation"],
      1,
      "Un sondage estime, à partir d'un échantillon représentatif, la répartition des opinions dans l'ensemble de la population."),
    q(5, "moyen", "socialisation-anticipatrice",
      "Un étudiant qui adopte déjà les codes de la profession qu'il vise connaît une socialisation :",
      ["primaire", "anticipatrice", "génétique", "régressive"],
      1,
      "La socialisation anticipatrice consiste à intérioser par avance les normes et valeurs d'un groupe auquel on souhaite appartenir."),
    q(6, "facile", "regime-politique",
      "Dans une démocratie représentative, le pouvoir politique est exercé :",
      ["directement par tous les citoyens au quotidien",
       "par un seul individu sans contrôle",
       "par des représentants élus par les citoyens",
       "par les entreprises privées"],
      2,
      "En démocratie représentative, les citoyens élisent des représentants qui exercent le pouvoir en leur nom, sous contrôle électoral."),
    q(7, "moyen", "sondage-marge-erreur",
      "Un sondage indique 52 % d'intentions de vote avec une marge d'erreur de 3 points. On peut dire que le résultat réel se situe probablement :",
      ["exactement à 52 %",
       "entre 49 % et 55 %",
       "au-dessus de 60 %",
       "en dessous de 40 %"],
      1,
      "Avec une marge d'erreur de plus ou moins 3 points, la vraie valeur est estimée entre 49 % et 55 % : le résultat n'est pas certain."),
    q(8, "facile", "pluralite-socialisation",
      "Dire que la socialisation est un processus « pluriel » signifie qu'elle :",
      ["ne concerne qu'une seule instance",
       "résulte de l'action de plusieurs instances (famille, école, pairs, médias...)",
       "est identique pour tous les individus",
       "s'achève à la naissance"],
      1,
      "La socialisation est plurielle car plusieurs instances y contribuent, parfois de façon complémentaire ou contradictoire."),
    q(9, "moyen", "reseaux-sociaux-numeriques",
      "Les réseaux sociaux numériques peuvent renforcer les inégalités sociales lorsque :",
      ["ils sont utilisés par tout le monde de la même manière",
       "les individus les mieux dotés en capital culturel en tirent davantage de ressources",
       "ils suppriment toute forme de relation sociale",
       "ils remplacent la banque centrale"],
      1,
      "L'usage des réseaux dépend des ressources sociales et culturelles : les mieux dotés en tirent plus de bénéfices, ce qui peut accroître les inégalités."),
    q(10, "facile", "vote",
      "L'abstention électorale désigne le fait, pour un inscrit, de :",
      ["voter blanc dans l'urne",
       "voter pour plusieurs candidats",
       "ne pas se rendre aux urnes le jour du scrutin",
       "voter par procuration"],
      2,
      "L'abstention correspond au fait de ne pas participer au vote alors qu'on est inscrit sur les listes électorales."),
    q(11, "moyen", "controle-social",
      "Avec l'individualisation des sociétés modernes, le contrôle social tend à devenir :",
      ["exclusivement informel et communautaire",
       "davantage formel, institutionnalisé et exercé à distance",
       "totalement inexistant",
       "identique à celui des sociétés traditionnelles"],
      1,
      "Dans les sociétés modernes, le contrôle social devient plus formel et institutionnalisé (police, justice, dispositifs de surveillance) qu'auparavant."),
    q(12, "moyen", "engagement",
      "Adhérer à une association et y militer bénévolement est une forme :",
      ["de consommation marchande",
       "d'engagement politique et social",
       "de création monétaire",
       "d'externalité négative"],
      1,
      "L'engagement associatif est une forme de participation politique et sociale non électorale, qui contribue à la vie démocratique."),
])

# ---------------------------------------------------------------------------
# 07 — TERMINALE — Croissance, sources et facteurs
# ---------------------------------------------------------------------------
FILES["07"] = ("terminale", [
    q(1, "facile", "croissance",
      "La croissance économique se définit comme :",
      ["la hausse générale des prix",
       "l'augmentation soutenue et durable de la production (PIB) d'un pays",
       "la baisse du chômage uniquement",
       "l'augmentation de la population"],
      1,
      "La croissance économique est l'accroissement durable de la production de biens et services, mesurée par la variation du PIB en volume."),
    q(2, "moyen", "pib-volume",
      "On mesure la croissance en « volume » (et non en valeur) afin de :",
      ["tenir compte de la hausse de la population",
       "inclure les variations de prix dans le calcul",
       "neutraliser l'effet de l'inflation sur le PIB",
       "mesurer uniquement les exportations"],
      2,
      "Le PIB en volume est corrigé de l'inflation : il isole l'évolution réelle des quantités produites, indépendamment des prix."),
    q(3, "moyen", "productivite-globale",
      "La productivité globale des facteurs (PGF) mesure :",
      ["la part de la croissance non expliquée par la hausse des quantités de travail et de capital",
       "le nombre total de salariés d'un pays",
       "le montant des impôts sur les entreprises",
       "la seule quantité de capital utilisée"],
      0,
      "La PGF (ou « résidu ») capte l'efficacité de la combinaison productive, liée notamment au progrès technique, au-delà de la simple hausse des facteurs."),
    q(4, "facile", "progres-technique",
      "Selon Schumpeter, le moteur central de la croissance de long terme est :",
      ["l'accumulation de dettes publiques",
       "l'innovation et la « destruction créatrice »",
       "la baisse des salaires",
       "la réduction du commerce international"],
      1,
      "Pour Schumpeter, l'innovation portée par les entrepreneurs entraîne une « destruction créatrice » qui renouvelle l'économie et soutient la croissance."),
    q(5, "moyen", "croissance-endogene",
      "Les théories de la croissance endogène insistent sur le fait que le progrès technique :",
      ["tombe du ciel, exogène à l'économie",
       "résulte de décisions d'investissement (R&D, éducation, infrastructures)",
       "dépend uniquement du climat",
       "n'a aucun lien avec la croissance"],
      1,
      "La croissance endogène (Romer, Lucas) montre que le progrès technique est produit par des investissements en capital humain, R&D et infrastructures."),
    q(6, "moyen", "coefficient-multiplicateur",
      "Un indice de production passe de la base 100 à 150. Le coefficient multiplicateur correspondant est :",
      ["1,5", "50", "0,5", "150"],
      0,
      "Coefficient multiplicateur = valeur d'arrivée / valeur de départ = 150 / 100 = 1,5."),
    q(7, "moyen", "capital-humain",
      "Le « capital humain » désigne :",
      ["le nombre d'habitants d'un pays",
       "l'ensemble des machines d'une usine",
       "l'ensemble des connaissances, compétences et qualifications des travailleurs",
       "le patrimoine financier des ménages"],
      2,
      "Le capital humain (Becker) regroupe les savoirs, compétences et expériences accumulés qui accroissent la productivité du travail."),
    q(8, "difficile", "taux-croissance-annuel-moyen",
      "Sur 10 ans, le PIB est multiplié par un coefficient de 1,10. Le taux de croissance global sur la période est :",
      ["110 %", "10 %", "1,1 %", "100 %"],
      1,
      "Un coefficient multiplicateur de 1,10 correspond à un taux de variation de (1,10 - 1) = 0,10 soit 10 % sur la période."),
    q(9, "facile", "institutions",
      "Selon les économistes institutionnalistes, la protection des droits de propriété favorise la croissance parce qu'elle :",
      ["décourage tout investissement",
       "incite les agents à investir et innover en sécurisant les gains futurs",
       "supprime la monnaie",
       "augmente mécaniquement les prix"],
      1,
      "Des droits de propriété bien définis et protégés sécurisent le rendement des investissements et encouragent l'innovation, soutenant la croissance."),
    q(10, "moyen", "limites-pib",
      "Une limite fréquemment reprochée au PIB comme indicateur est qu'il :",
      ["mesure trop bien le bien-être et l'environnement",
       "ignore la production non marchande domestique et les atteintes à l'environnement",
       "surestime toujours les inégalités",
       "ne peut jamais être calculé"],
      1,
      "Le PIB ne comptabilise pas le travail domestique, le bénévolat, ni les dégradations environnementales : d'où des indicateurs alternatifs (IDH, empreinte écologique)."),
    q(11, "difficile", "croissance-cumul",
      "Un PIB croît de 2 % puis de 3 % l'année suivante. Le taux de croissance cumulé sur les deux ans est d'environ :",
      ["5 %", "6 %", "5,06 %", "1,5 %"],
      2,
      "Coefficient global = 1,02 x 1,03 = 1,0506, soit un taux cumulé d'environ 5,06 % (les taux ne s'additionnent pas exactement)."),
    q(12, "moyen", "investissement",
      "L'investissement (formation brute de capital fixe) contribue à la croissance car il :",
      ["réduit la capacité de production",
       "augmente et modernise le stock de capital productif",
       "diminue toujours la productivité",
       "correspond à une consommation intermédiaire"],
      1,
      "L'investissement accroît et renouvelle le capital fixe, ce qui augmente les capacités de production et, via le progrès technique incorporé, la productivité."),
])

# ---------------------------------------------------------------------------
# 08 — TERMINALE — Commerce international, chômage
# ---------------------------------------------------------------------------
FILES["08"] = ("terminale", [
    q(1, "facile", "avantage-comparatif",
      "Selon Ricardo, un pays a intérêt à se spécialiser dans la production pour laquelle il détient :",
      ["un avantage absolu sur tous les biens",
       "un avantage comparatif, c'est-à-dire le coût relatif le plus faible",
       "la population la plus nombreuse",
       "les impôts les plus élevés"],
      1,
      "La théorie de l'avantage comparatif montre qu'un pays gagne à se spécialiser là où son coût relatif (d'opportunité) est le plus faible, même sans avantage absolu."),
    q(2, "moyen", "libre-echange-protectionnisme",
      "Le protectionnisme désigne une politique visant à :",
      ["supprimer toutes les frontières commerciales",
       "protéger la production nationale par des droits de douane ou des quotas",
       "interdire toute production nationale",
       "fixer le taux d'intérêt directeur"],
      1,
      "Le protectionnisme cherche à protéger les producteurs nationaux de la concurrence étrangère (droits de douane, quotas, normes)."),
    q(3, "moyen", "commerce-intra-firme",
      "Le commerce intra-firme correspond aux échanges :",
      ["entre deux États souverains",
       "entre filiales d'une même firme multinationale",
       "entre une banque et sa clientèle",
       "entre l'État et les ménages"],
      1,
      "Le commerce intra-firme désigne les flux de biens et services entre les différentes entités (filiales) d'une même firme multinationale."),
    q(4, "facile", "chomage-structurel",
      "Le chômage structurel provient principalement :",
      ["d'un ralentissement temporaire de l'activité",
       "d'une inadéquation durable entre qualifications offertes et emplois demandés",
       "des congés payés",
       "d'une hausse ponctuelle des exportations"],
      1,
      "Le chômage structurel résulte de déséquilibres durables (qualifications, mobilité, institutions du marché du travail), au-delà des fluctuations conjoncturelles."),
    q(5, "facile", "chomage-conjoncturel",
      "Le chômage conjoncturel est lié :",
      ["au ralentissement de l'activité économique (baisse de la demande)",
       "aux progrès technologiques permanents",
       "à la rigidité des qualifications",
       "à la démographie de long terme"],
      0,
      "Le chômage conjoncturel apparaît lors des phases de ralentissement ou de récession, quand la demande et donc la production baissent."),
    q(6, "moyen", "cout-du-travail",
      "Selon l'analyse néoclassique, un salaire minimum fixé au-dessus du salaire d'équilibre peut :",
      ["supprimer tout chômage",
       "créer un chômage en rendant certains travailleurs trop coûteux à embaucher",
       "augmenter mécaniquement la demande de travail",
       "n'avoir aucun effet sur l'emploi"],
      1,
      "Pour l'analyse néoclassique, un salaire plancher supérieur à l'équilibre réduit la demande de travail et peut engendrer un chômage des moins qualifiés."),
    q(7, "moyen", "taux-de-variation",
      "Les exportations d'un pays passent de 400 à 460 milliards d'euros. Quel est le taux de variation ?",
      ["6 %", "60 %", "15 %", "115 %"],
      2,
      "Taux = (460 - 400) / 400 = 60 / 400 = 0,15 soit 15 %."),
    q(8, "moyen", "balance-commerciale",
      "La balance commerciale d'un pays est excédentaire lorsque :",
      ["ses importations dépassent ses exportations",
       "ses exportations de biens dépassent ses importations",
       "son PIB augmente",
       "son taux de chômage baisse"],
      1,
      "La balance commerciale est excédentaire quand la valeur des exportations de biens excède celle des importations."),
    q(9, "facile", "dotation-facteurs",
      "Le modèle HOS (Heckscher-Ohlin-Samuelson) explique la spécialisation par :",
      ["la seule taille de la population",
       "les dotations relatives en facteurs de production (travail, capital)",
       "le niveau des impôts locaux",
       "la couleur du drapeau national"],
      1,
      "Le modèle HOS montre qu'un pays exporte les biens intensifs dans le facteur dont il est relativement bien doté."),
    q(10, "moyen", "flexibilite",
      "Les politiques de « flexibilisation » du marché du travail visent surtout à réduire le chômage :",
      ["conjoncturel par la relance budgétaire",
       "structurel en assouplissant les règles d'embauche et de licenciement",
       "en augmentant fortement les cotisations",
       "en fermant les frontières commerciales"],
      1,
      "La flexibilisation cible le chômage structurel : on assouplit les contrats et le coût d'ajustement de la main-d'œuvre pour faciliter l'appariement."),
    q(11, "moyen", "delocalisation",
      "Une entreprise qui transfère une partie de sa production vers un pays à moindre coût réalise :",
      ["une délocalisation",
       "une externalité positive",
       "une création monétaire",
       "un autofinancement"],
      0,
      "La délocalisation consiste à déplacer une activité productive vers un autre pays, souvent pour bénéficier de coûts (salariaux, fiscaux) plus faibles."),
    q(12, "difficile", "gains-echange",
      "Un effet négatif possible du libre-échange, souvent souligné, est :",
      ["l'élargissement du choix des consommateurs",
       "la baisse des prix pour les acheteurs",
       "la disparition d'emplois dans les secteurs exposés à la concurrence",
       "la diffusion accélérée des innovations"],
      2,
      "Le libre-échange apporte des gains globaux mais crée des perdants : certains secteurs peu compétitifs perdent des emplois, d'où la nécessité de politiques d'accompagnement."),
])

# ---------------------------------------------------------------------------
# 09 — TERMINALE — Politique économique, inflation, chômage
# ---------------------------------------------------------------------------
FILES["09"] = ("terminale", [
    q(1, "facile", "politique-conjoncturelle",
      "Une politique de relance keynésienne consiste notamment à :",
      ["réduire fortement les dépenses publiques",
       "augmenter la dépense publique pour soutenir la demande globale",
       "relever les taux d'intérêt directeurs",
       "diminuer les salaires nominaux"],
      1,
      "La relance keynésienne stimule la demande globale (dépenses publiques, baisses d'impôts) pour relancer l'activité et l'emploi."),
    q(2, "facile", "politique-monetaire",
      "Pour lutter contre une inflation trop élevée, la banque centrale peut :",
      ["augmenter ses taux d'intérêt directeurs",
       "distribuer directement de l'argent aux ménages",
       "baisser fortement les taux directeurs",
       "supprimer la monnaie unique"],
      0,
      "En relevant ses taux directeurs, la banque centrale renchérit le crédit, ralentit la demande et freine ainsi la hausse des prix."),
    q(3, "moyen", "inflation-indice",
      "L'indice des prix à la consommation passe de 100 à 104 en un an. Le taux d'inflation est de :",
      ["104 %", "4 %", "0,4 %", "40 %"],
      1,
      "Taux d'inflation = (104 - 100) / 100 = 4 %."),
    q(4, "moyen", "politique-offre",
      "Une politique de l'offre vise principalement à :",
      ["soutenir la demande par des transferts aux ménages",
       "améliorer la compétitivité et les conditions de production des entreprises",
       "augmenter les droits de douane",
       "rationner la consommation"],
      1,
      "Les politiques de l'offre cherchent à améliorer les conditions de production (coût du travail, fiscalité, innovation) pour renforcer la compétitivité."),
    q(5, "facile", "deficit-public",
      "Il y a déficit public lorsque :",
      ["les recettes de l'État dépassent ses dépenses",
       "les dépenses publiques dépassent les recettes publiques sur une année",
       "la dette est totalement remboursée",
       "l'inflation devient négative"],
      1,
      "Le déficit public correspond à un solde négatif : les dépenses des administrations publiques excèdent leurs recettes sur l'exercice."),
    q(6, "moyen", "effet-multiplicateur",
      "L'effet multiplicateur keynésien signifie qu'une dépense publique supplémentaire :",
      ["n'a aucun effet sur le revenu national",
       "engendre une hausse du revenu national supérieure à la dépense initiale",
       "réduit systématiquement l'emploi",
       "diminue la demande globale"],
      1,
      "Grâce aux revenus redistribués et redépensés en chaîne, une dépense initiale génère une augmentation plus que proportionnelle du revenu national."),
    q(7, "moyen", "inflation-cout",
      "Une « inflation par les coûts » est provoquée par :",
      ["une baisse de la demande globale",
       "une hausse des coûts de production (matières premières, salaires) répercutée sur les prix",
       "une politique monétaire restrictive",
       "une chute des prix du pétrole"],
      1,
      "L'inflation par les coûts résulte d'une hausse des coûts de production (énergie, salaires) que les entreprises répercutent sur leurs prix de vente."),
    q(8, "difficile", "pouvoir-achat",
      "Le salaire nominal augmente de 2 % et les prix de 3 %. Le pouvoir d'achat du salaire :",
      ["augmente d'environ 1 %",
       "reste stable",
       "diminue d'environ 1 %",
       "augmente de 5 %"],
      2,
      "Le salaire réel varie approximativement comme 2 % - 3 % = -1 % : le pouvoir d'achat baisse d'environ 1 % car les prix montent plus vite que le salaire."),
    q(9, "facile", "politique-monetaire-relance",
      "Pour soutenir l'activité en période de faible croissance, la banque centrale peut :",
      ["baisser ses taux d'intérêt directeurs",
       "augmenter les impôts des ménages",
       "réduire la masse monétaire brutalement",
       "interdire le crédit bancaire"],
      0,
      "En baissant ses taux directeurs, la banque centrale rend le crédit moins cher, ce qui favorise investissement et consommation."),
    q(10, "moyen", "policy-mix",
      "Le « policy mix » désigne :",
      ["la combinaison des politiques budgétaire et monétaire",
       "un mélange de plusieurs impôts locaux",
       "l'ensemble des politiques de l'entreprise",
       "un indice des prix particulier"],
      0,
      "Le policy mix est l'articulation entre politique budgétaire (État) et politique monétaire (banque centrale) pour atteindre les objectifs macroéconomiques."),
    q(11, "moyen", "contrainte-exterieure",
      "Une politique de relance dans un seul pays très ouvert peut être limitée car :",
      ["elle réduit toujours les importations",
       "une partie de la demande supplémentaire se porte sur des produits importés",
       "elle supprime la dette publique",
       "elle fait automatiquement baisser les prix"],
      1,
      "Dans une économie ouverte, la relance « fuit » vers l'extérieur : une part de la demande stimule les importations plutôt que la production nationale (contrainte extérieure)."),
    q(12, "moyen", "chomage-inflation",
      "La courbe de Phillips exprime, à court terme, une relation :",
      ["positive entre inflation et taux d'intérêt",
       "d'arbitrage entre inflation et chômage (l'un baisse quand l'autre monte)",
       "sans aucun lien entre les variables",
       "entre PIB et population"],
      1,
      "La courbe de Phillips met en évidence, à court terme, une relation inverse entre le taux de chômage et le taux d'inflation."),
])

# ---------------------------------------------------------------------------
# 10 — TERMINALE — Stratification, mobilité sociale, école
# ---------------------------------------------------------------------------
FILES["10"] = ("terminale", [
    q(1, "facile", "mobilite-sociale",
      "La mobilité sociale intergénérationnelle mesure :",
      ["les déménagements d'une région à l'autre",
       "les changements de position sociale entre parents et enfants",
       "les variations du PIB entre deux années",
       "les mouvements de capitaux entre pays"],
      1,
      "La mobilité sociale intergénérationnelle compare la position sociale des individus à celle de leurs parents (souvent le père)."),
    q(2, "moyen", "table-mobilite",
      "Une table de mobilité (dite « de destinée ») se lit :",
      ["en pourcentages en ligne, à partir de l'origine sociale vers la position atteinte",
       "uniquement en valeurs absolues",
       "en comparant deux pays",
       "en additionnant les colonnes de prix"],
      0,
      "Une table de destinée se lit en ligne : pour une origine sociale donnée, elle indique la répartition des enfants selon la catégorie qu'ils atteignent."),
    q(3, "facile", "mobilite-verticale",
      "Un enfant d'ouvrier qui devient cadre connaît une mobilité :",
      ["horizontale", "immobile",
       "ascendante (verticale)", "géographique"],
      2,
      "Passer d'une origine ouvrière à une position de cadre est une mobilité verticale ascendante (montée dans la hiérarchie sociale)."),
    q(4, "moyen", "mobilite-structurelle",
      "La mobilité structurelle est celle qui résulte :",
      ["de l'évolution de la structure des emplois entre deux générations",
       "des seuls efforts individuels",
       "du hasard des naissances",
       "de la politique monétaire"],
      0,
      "La mobilité structurelle (ou forcée) provient des transformations de la structure socioprofessionnelle (moins d'agriculteurs, plus de cadres), indépendamment des mérites individuels."),
    q(5, "facile", "reproduction-sociale",
      "Selon Bourdieu, l'école contribue souvent à la « reproduction sociale » car :",
      ["elle supprime toutes les inégalités de départ",
       "elle valorise un capital culturel inégalement réparti selon l'origine sociale",
       "elle distribue les diplômes au hasard",
       "elle n'a aucun effet sur les trajectoires"],
      1,
      "Pour Bourdieu, l'école valorise un capital culturel proche de celui des classes favorisées, ce qui tend à reproduire les positions sociales d'origine."),
    q(6, "moyen", "coefficient-multiplicateur",
      "La part des diplômés du supérieur passe de 20 % à 40 % dans une génération. Cette part a été multipliée par :",
      ["2", "20", "0,5", "4"],
      0,
      "Coefficient multiplicateur = 40 / 20 = 2 : la proportion a doublé (elle a augmenté de 20 points, soit +100 %)."),
    q(7, "moyen", "capital-culturel",
      "Le capital culturel, selon Bourdieu, peut prendre une forme « incorporée » qui correspond :",
      ["aux diplômes obtenus",
       "aux livres et tableaux possédés",
       "aux dispositions, savoirs et manières intériorisés durablement",
       "au patrimoine financier"],
      2,
      "Le capital culturel incorporé désigne les dispositions durables (langage, goûts, savoir-être) intériorisées par la socialisation, distinctes des formes objectivée (biens) et institutionnalisée (diplômes)."),
    q(8, "facile", "classes-sociales",
      "Pour Karl Marx, ce qui définit d'abord l'appartenance à une classe sociale, c'est :",
      ["le niveau de revenu déclaré aux impôts",
       "la place occupée dans les rapports de production (propriété ou non des moyens de production)",
       "le lieu de résidence",
       "le diplôme obtenu"],
      1,
      "Chez Marx, la classe se définit par la place dans les rapports de production : détenir ou non les moyens de production oppose bourgeoisie et prolétariat."),
    q(9, "moyen", "fluidite-sociale",
      "La fluidité sociale désigne :",
      ["l'ampleur totale des changements de position, structurels inclus",
       "l'égalité des chances d'accès aux positions sociales indépendamment de l'origine",
       "le nombre de déménagements annuels",
       "la vitesse de circulation de la monnaie"],
      1,
      "La fluidité sociale mesure l'indépendance entre origine et position sociales, c'est-à-dire l'égalité des chances, en neutralisant la mobilité structurelle."),
    q(10, "facile", "declassement",
      "Un individu occupant une position sociale inférieure à celle de ses parents connaît une mobilité :",
      ["ascendante", "horizontale",
       "descendante (déclassement)", "structurelle ascendante"],
      2,
      "Occuper une position plus basse que celle de ses parents correspond à une mobilité descendante, souvent qualifiée de déclassement."),
    q(11, "moyen", "massification-scolaire",
      "La « massification scolaire » désigne :",
      ["la baisse du nombre d'élèves scolarisés",
       "l'accès d'un nombre beaucoup plus grand d'élèves à des niveaux d'études élevés",
       "la disparition des diplômes",
       "la privatisation de toutes les écoles"],
      1,
      "La massification scolaire est l'allongement des études et l'accès élargi de nombreux élèves aux niveaux supérieurs, sans pour autant garantir la démocratisation (égalité des chances)."),
    q(12, "difficile", "lecture-table",
      "Dans une table de destinée, la case « 45 % » à l'intersection origine cadre / position cadre signifie que :",
      ["45 % de tous les cadres ont un père cadre",
       "45 % des fils de cadres sont eux-mêmes devenus cadres",
       "45 % de la population est cadre",
       "les cadres représentent 45 % du PIB"],
      1,
      "Une table de destinée se lit en ligne à partir de l'origine : parmi les fils de cadres, 45 % occupent eux-mêmes une position de cadre."),
])

# ---------------------------------------------------------------------------
for nn, (niveau, questions) in FILES.items():
    assert len(questions) == 12, (nn, len(questions))
    data = {
        "id": f"bb-ses-{nn}",
        "titre": f"Bac blanc — SES (n° {nn})",
        "examen": "Bac blanc",
        "niveau": niveau,
        "matiere": "ses",
        "statut": "brouillon",
        "relu_par": None,
        "consigne": "Une seule réponse correcte par question. Économie, sociologie et science politique.",
        "questions": questions,
    }
    path = os.path.join(OUT, f"bb-ses-{nn}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    # distribution of correct answer positions
    dist = [0, 0, 0, 0]
    for q_ in questions:
        dist[q_["reponse"]] += 1
    print(f"bb-ses-{nn}.json  niveau={niveau:9s}  positions={dist}")

print("Généré:", len(FILES), "fichiers")
